import type { Metadata } from "next";
import { Geist, Geist_Mono, Poetsen_One, Salsa } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import DiceBackground from "@/components/DiceBackground";
import ClientConfig from "@/components/ClientConfig";
import { client } from "@/src/api/generated/client.gen";

// Change the base URL dynamically
client.setConfig({
  baseUrl: process.env.BACKEND_URL || "http://localhost:3000",
  credentials: "include",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poetsenOne = Poetsen_One({
  weight: "400",
  variable: "--font-poetsen-one",
  subsets: ["latin"],
});

const salsa = Salsa({
  weight: "400",
  variable: "--font-salsa",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${poetsenOne.variable} ${salsa.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClientConfig />
        <Navbar />
        <DiceBackground />
        {children}
      </body>
    </html>
  );
}
